name: Task Manager CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: backend

      - name: Copy .env.example to .env
        run: cp .env.example .env
        working-directory: backend

      - name: Generate application key
        run: php artisan key:generate
        working-directory: backend

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: backend

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
        working-directory: backend

      - name: Run Test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
        working-directory: backend
